const ROUTES = {
  getAllProducts: () => '/products',
  getProduct: (slug: string) => `/products/${slug}`,
  getNewArrival: () => `/getNewArrivalProducts`,
  getTopFurnitureCategory: () => '/top-categories',
  getHomePageBanner: () => '/banners',
  getBestSellerProducts: () => '/best-seller-products',
  getMenus: () => '/get-menus',
  categoryDetail: (slug: string | any) => `/categories/${slug}`,
  getCartItems: () => '/carts',
  postCartItems: () => '/carts',
  updateCartItem: (id) => `/carts/${id}`,
  login: () => '/token',
  forgotPassword: () => '/forget-password',
  verifyToken: () => '/verify-forget-password-token',
  resetPassword: () => '/reset-password',
  loginAuth: () => '/social-login-token',
  logingUsingOTP: () => '/send-otp-code',
  logingUSingOTPregister: () => `/send-otp-register`,
  verifyOtp: () => '/verify-otp-code',
  verifyOtpRegister: () => `/verify-otp-register`,
  registerUser: () => `/register`,
  bestSellerProductCategory: (slug: string | any) =>
    `/best-seller-products?category_id=${slug}`,
  shopByMaterialCategory: (slug: string | any) =>
    `/shopbymaterial?parent=${slug}`,
  getSimmilerProduct: (slug: string | any) => `/getSimilarProducts/${slug}`,
  getOtherOrderProductDetail: (slug: string | any) =>
    `/getOtherOrderProducts/${slug}`,
  lastViewdProduct: () => `/last-viewed-products`,
  addlastViewdProduct: () => '/add-last-viewed-products',
  validateProduct: () => `/carts/validateCartProduct`,
  userAddress: () => '/address',
  updateUserAddress: (id) => `/address/${id}`,
  categoryAdvertisment: () => `/advertisement-banners?limit=1`,
  categoryAdvertismentData: (id: any) =>
    `/advertisement-banners?limit=2&category_id=${id}`,

  couponList: () => '/coupons',
  productListing: (id: number) => `/product-list?category=${id}`,
  addToWishList: () => '/wishlists/toggle',
  removeFromWishList: (id: number | string) => `/wishlists/${id}`,
  getWishList: (page?: number | string) =>
    page ? `/wishlists?page=${page}` : `/wishlists`,
  postReview: () => '/reviews',
  checkpostcode: () => `/check-postcode`,
  search: () => `/getSearchList`,
  invoiceUrl: () => `/download-invoice-url`,
  getSearchProductList: (product_search: string | number | string[]) =>
    `/getManualSearchList?product_search=${product_search}`,

  getUserDetails: () => '/me',
  deteteAddress: (id) => `/address/${id}`,
  postOrder: () => `/orders`,
  downloadInvoie: () => '/download-invoice-url',
  getOrderDetails: (orderId: any) => `/orders/${orderId}`,
  attributeFilter: (slug) =>
    slug ? `/attributes?category_id=${slug}` : undefined,
  aboutUs: () => `/show-static-page?slug=about-us`,
  contactus: () => `/show-static-page?slug=contactus`,
  career: () => `/show-static-page?slug=career`,
  media: () => `/get-media-list`,
  testimonial: () => `/testimonials`,
  stores: () => `/our-stores`,
  storesSearch: (searchTerm: string) => `/our-stores?search=${searchTerm}`,
  storeDetail: (id: any) => `/our-stores/${id}`,
  updateUser: (id: number | string) => `/users/${id}`,
  myorders: (page: number | string) =>
    page ? `/orders?page=${page}` : `/orders`,
  reviewMedia: () => `/reviews/media`,
  orderPayment: () => `/orders/payment`,
  applyCoupon: () => `/coupons/apply`,
  verifyCoupon: () => `/coupons/verify`,
  styleShowcase: (id: any) => `/style-showcase/${id}`,
  getAllStates: () => '/get-states',
  helpDesk: () => `/send-helpdesk-mail`,
  getFaq: () => `/get-faq-type`,
  getFaqId: (id: any) => `/get-general-faq?faq_type_id=${id}`,
  cancelOrder: (id: any) => `/orders/${id}/cancel`,
  footerData: () => `/get-menus?id=2 `,
  getFaqIdSearch: (search: any) => `/get-general-faq?search=${search}`,
  staticPage: (slug: any) => `/show-static-page?slug=${slug}`,
  accountRemoval: () => `/delete-user-request`,
};

export default ROUTES;
